name: CI Develop - builder

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  builder-image:
    name: Contruir a imagem
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      - name: Limpar diretório
        run: |
          pwd
          cd /home/morgado/actions-runner/_work
          rm -rf /home/morgado/actions-runner/_work/afinese/
      - name: Clonar repositório develop
        run: |
          cd /home/morgado/actions-runner/_work
          git clone --branch develop https://github.com/EmersonMorgado/afinese.git
      - name: Contruindo as imagem
        run: |
          pwd
#          docker run -it --rm --name my-maven-project -v /home/morgado/actions-runner/_work/afinese:/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean install
           
 #     - name: Clone do repositorio afinese no branch develop
 #       run: git clone --branch develop https://github.com/EmersonMorgado/afinese.git
 #     - name: Iniciar builder
 #       run: |
 #         cd afinese
 #         ls
 #         docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean install
 #     - name: Exibir os arquivos .jar na pasta target
 #       run: ls target/*.jar
