name: CI Create Docker Image 

# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["CI Develop - builder"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: ver variave $GITHUB_WORKSPACE
        run: $GITHUB_WORKSPACE
